# Generated by Django 3.0.5 on 2022-07-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200131_0131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['important', 'priority', '-created', 'status']},
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2),
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Done')], default=1),
        ),
    ]
