# Generated by Django 3.0.5 on 2022-07-11 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20220711_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['important', '-priority', '-created', 'status']},
        ),
    ]
